// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH070RhHRkdU6tTEpMQTgajW9N4WnOE-c',
    appId: '1:14824871317:web:b3647ea195d501c64e529c',
    messagingSenderId: '14824871317',
    projectId: 'dictionary-424c8',
    authDomain: 'dictionary-424c8.firebaseapp.com',
    storageBucket: 'dictionary-424c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3V6JOKeQFHrP8CLmfjDeUNx4s9ZBZNtI',
    appId: '1:14824871317:android:ac426b4164ac65544e529c',
    messagingSenderId: '14824871317',
    projectId: 'dictionary-424c8',
    storageBucket: 'dictionary-424c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8WMLM5PAPQRqWo8vra2vwMJkvVGvUN-c',
    appId: '1:14824871317:ios:b879ed968fe2305d4e529c',
    messagingSenderId: '14824871317',
    projectId: 'dictionary-424c8',
    storageBucket: 'dictionary-424c8.appspot.com',
    iosBundleId: 'com.example.dictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8WMLM5PAPQRqWo8vra2vwMJkvVGvUN-c',
    appId: '1:14824871317:ios:5b9d923bed1efe344e529c',
    messagingSenderId: '14824871317',
    projectId: 'dictionary-424c8',
    storageBucket: 'dictionary-424c8.appspot.com',
    iosBundleId: 'com.example.dictionary.RunnerTests',
  );
}
